import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <header
          style={{
            backgroundColor: "cyan",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header> */}
        <Header/>
        {children}
        {/* <footer
          style={{
            backgroundColor: "aliceblue",
            padding: "1rem",
          }}
        >
          <p>footer</p>
        </footer> */}
        <Footer/>
      </body>
    </html>
  );
}
